So I will admit this has been more of an exercise in learning code for me, so the following might be way off. But I was messing with some things trying to see if I could fit a classifier for the marine and non-marine facies and formations seperately. It looks like there are some discrepancies in the NM_M data not corresponding to the correct facies. Any thoughts? Note, this may also apply to the validation data. See below.

In [1]:
import pandas as pd

from pandas import set_option
set_option("display.max_rows", None)

training_data = pd.read_csv('facies_vectors.csv')

In [9]:
PE_mask = training_data['PE'].notnull().values
training_data = training_data[PE_mask]

In [10]:
training_data.describe()

,Facies,Depth,GR,ILD_log10,DeltaPHI,PHIND,PE,NM_M,RELPOS
count,3232.000000,3232.000000,3232.000000,3232.000000,3232.000000,3232.000000,3232.000000,3232.000000,3232.000000
mean,4.422030,2875.824567,66.135769,0.642719,3.559642,13.483213,3.725014,1.498453,0.520287
std,2.504243,131.006274,30.854826,0.241845,5.228948,7.698980,0.896152,0.500075,0.286792
min,1.000000,2573.500000,13.250000,-0.025949,-21.832000,0.550000,0.200000,1.000000,0.010000
25%,2.000000,2791.000000,46.918750,0.492750,1.163750,8.346750,3.100000,1.000000,0.273000
50%,4.000000,2893.500000,65.721500,0.624437,3.500000,12.150000,3.551500,1.000000,0.526000
75%,6.000000,2980.000000,79.626250,0.812735,6.432500,16.453750,4.300000,2.000000,0.767250
max,9.000000,3122.500000,361.150000,1.480000,18.600000,84.400000,8.094000,2.000000,1.000000

Here I am checking the non-marine facies 1,2,3 with the NM_M label. It looks like there are some discrepancies, where the Faceis label indicates its NM but the NM_M label indicates marine. Does it really matter because its a relatively small number? But what does this say about our data and ability to make predictions?

In [11]:
td_NM = training_data.loc[training_data['Facies'].isin([1,2,3])]
td_NM.loc[td_NM['NM_M'].isin([2])]

,Facies,Formation,Well Name,Depth,GR,ILD_log10,DeltaPHI,PHIND,PE,NM_M,RELPOS
2527,3,B3 SH,CROSS H CATTLE,2696.5,103.582,0.682867,6.600,12.400,3.400,2,1.000
2579,2,B4 SH,CROSS H CATTLE,2721.5,74.660,0.474653,9.000,17.700,3.515,2,1.000
2645,3,B5 SH,CROSS H CATTLE,2754.5,64.146,0.621799,-18.700,23.450,2.502,2,0.100
2777,2,C LM,CROSS H CATTLE,2837.0,78.049,0.618884,-12.100,21.450,2.608,2,0.147
2778,2,C LM,CROSS H CATTLE,2837.5,75.925,0.631545,-6.900,19.250,2.826,2,0.132
2779,3,C LM,CROSS H CATTLE,2838.0,77.553,0.666424,-8.400,22.600,2.840,2,0.118
2780,2,C LM,CROSS H CATTLE,2838.5,71.921,0.710963,-6.100,23.350,2.899,2,0.103
2781,3,C LM,CROSS H CATTLE,2839.0,61.939,0.745231,-6.500,22.850,2.917,2,0.088
2782,3,C LM,CROSS H CATTLE,2839.5,51.987,0.765669,-3.800,18.700,3.022,2,0.074
2783,3,C LM,CROSS H CATTLE,2840.0,41.019,0.772762,1.100,13.450,3.298,2,0.059
2944,2,B2 SH,NOLAN,2932.0,63.938,0.782000,1.615,6.930,3.393,2,0.050
2967,3,B2 SH,NOLAN,2943.5,60.250,0.651000,-5.054,17.847,4.438,2,1.000
2989,3,B3 SH,NOLAN,2954.5,55.469,0.795000,1.023,4.397,4.762,2,0.083
2990,3,B3 SH,NOLAN,2955.0,81.375,0.741000,2.505,6.675,4.004,2,0.042
3776,3,A1 LM,CHURCHMAN BIBLE,2933.0,71.563,0.772000,3.478,22.157,2.416,2,0.870
3777,3,A1 LM,CHURCHMAN BIBLE,2933.5,75.375,0.746000,-0.136,20.595,2.496,2,0.859
3779,3,A1 LM,CHURCHMAN BIBLE,2934.5,79.375,0.730000,2.966,20.960,2.967,2,0.837
3780,3,A1 LM,CHURCHMAN BIBLE,2935.0,79.438,0.734000,1.488,19.020,3.406,2,0.826
3911,3,B2 SH,CHURCHMAN BIBLE,3000.5,207.125,0.707000,-0.923,22.896,2.350,2,0.063
3912,3,B2 SH,CHURCHMAN BIBLE,3001.0,221.125,0.664000,-9.690,39.427,2.043,2,0.031
3953,3,B3 SH,CHURCHMAN BIBLE,3021.5,87.875,0.500000,3.797,9.680,3.201,2,0.033
3982,2,B4 SH,CHURCHMAN BIBLE,3036.0,69.500,0.837000,2.843,8.387,3.268,2,0.071

In [12]:
td_M = training_data.loc[training_data['Facies'].isin([4,5,6,7,8,9])]
td_M.loc[td_M['NM_M'].isin([1])]

,Facies,Formation,Well Name,Depth,GR,ILD_log10,DeltaPHI,PHIND,PE,NM_M,RELPOS
1227,6,B4 LM,SHANKLE,2924.0,26.060,0.725000,-12.900,16.170,4.400,1,0.857
2356,8,A1 SH,CROSS H CATTLE,2608.5,85.898,0.540455,5.100,16.050,3.099,1,0.013
2457,4,B1 SH,CROSS H CATTLE,2660.0,94.469,0.308351,-8.000,33.600,2.280,1,0.121
2465,4,B1 SH,CROSS H CATTLE,2664.0,104.128,0.501333,12.500,17.350,3.150,1,0.015
2476,8,B1 LM,CROSS H CATTLE,2669.5,95.638,0.856910,-6.100,11.950,3.230,1,1.000
2511,5,B2 SH,CROSS H CATTLE,2688.5,59.734,0.578868,6.500,16.150,3.524,1,0.296
2512,5,B2 SH,CROSS H CATTLE,2689.0,52.386,0.581495,9.900,13.850,3.578,1,0.278
2513,5,B2 SH,CROSS H CATTLE,2689.5,50.751,0.585574,11.400,11.700,3.553,1,0.259
2514,5,B2 SH,CROSS H CATTLE,2690.0,50.034,0.593175,10.800,10.500,3.491,1,0.241
2524,4,B2 SH,CROSS H CATTLE,2695.0,90.179,0.747334,7.000,10.900,3.414,1,0.056
2525,4,B2 SH,CROSS H CATTLE,2695.5,94.523,0.737987,7.300,11.150,3.399,1,0.037
2663,5,B5 SH,CROSS H CATTLE,2765.5,75.264,0.326131,-10.600,27.600,2.605,1,0.115
2664,5,B5 SH,CROSS H CATTLE,2766.0,72.400,0.289812,-14.800,32.300,2.436,1,0.077
2686,8,B5 LM,CROSS H CATTLE,2777.0,110.121,0.488833,4.000,16.600,3.331,1,1.000
2687,8,B5 LM,CROSS H CATTLE,2777.5,111.355,0.488127,-11.500,27.450,2.720,1,0.984
2688,5,B5 LM,CROSS H CATTLE,2778.0,104.598,0.487421,-12.300,31.950,2.558,1,0.968
2827,5,A1 SH,NOLAN,2873.5,73.688,0.310000,6.614,17.409,2.922,1,0.091
2828,5,A1 SH,NOLAN,2874.0,76.250,0.295000,7.123,19.977,2.981,1,0.068
2891,8,A1 LM,NOLAN,2905.5,79.250,0.671000,1.088,17.369,3.490,1,1.000
2924,8,B1 LM,NOLAN,2922.0,48.281,0.596000,3.010,19.402,2.906,1,0.029
3051,5,B4 LM,NOLAN,2985.5,66.813,0.567000,6.296,23.489,3.065,1,0.083
3052,8,B4 LM,NOLAN,2986.0,38.781,0.588000,1.993,17.245,4.199,1,0.042
3063,6,B4 LM,NOLAN,2991.5,54.031,0.385000,3.715,15.084,2.940,1,1.000
3070,4,B5 LM,NOLAN,2995.0,48.031,-0.019000,5.381,20.059,3.592,1,0.125
3143,8,C LM,NOLAN,3031.5,81.125,0.597000,5.830,19.023,3.131,1,0.053
3144,8,C LM,NOLAN,3032.0,58.188,0.643000,6.517,15.260,3.334,1,0.026
3880,5,B1 LM,CHURCHMAN BIBLE,2985.0,60.219,0.545000,3.448,27.606,2.652,1,0.042
3922,7,B2 SH,CHURCHMAN BIBLE,3006.0,67.500,0.696000,-1.373,37.750,2.102,1,0.167
3968,8,B3 LM,CHURCHMAN BIBLE,3029.0,47.000,0.757000,-4.656,18.133,3.836,1,0.071
3996,8,B4 LM,CHURCHMAN BIBLE,3044.0,49.438,0.752000,-8.496,19.434,4.785,1,0.063
4011,8,B5 LM,CHURCHMAN BIBLE,3054.0,33.906,0.641000,1.365,4.739,4.879,1,0.167

This indicates that there may be a small amount of Facies data that does not fit with the classification NM_M. I only want to point out some potential outliers that may influence the results negatively, not say 'this is wrong!'. Although, I'm not sure what a good solution is. Do we remove these data?

So what does our validation data look like? Maybe these wells also contain some discrepancies?

But since we don't have the Facies data, we can only describe the relationship between the non-marine and marine Formations.

In [14]:
validation = pd.read_csv('validation_data_nofacies.csv')

In [14]:
#I was enumerating the Formations, but for clarity, just left as original
#for i, value in enumerate(validation['Formation'].unique()):
#    validation.loc[validation['Formation'] == value, 'Formation'] = i

In [16]:
vd = validation.loc[validation['Formation'].isin(['A1 SH', 'B1 SH', 'B2 SH', 'B3 SH', 'B4 SH', 'B5 SH', 'C SH'])]
vd.loc[vd['NM_M'].isin([2])]

,Formation,Well Name,Depth,GR,ILD_log10,DeltaPHI,PHIND,PE,NM_M,RELPOS
667,B3 SH,CRAWFORD,3078.0,110.210,0.792,0.27,14.14,2.678,2,0.036
702,B4 SH,CRAWFORD,3095.5,55.601,0.610,2.42,7.82,3.146,2,0.063
739,B5 SH,CRAWFORD,3114.0,55.757,0.900,2.86,7.09,3.514,2,0.056

In [17]:
vd_o = validation.loc[validation['Formation'].isin(['A1 LM', 'B1 LM', 'B2 LM', 'B3 LM', 'B4 LM', 'B5 LM', 'C LM'])]
vd_o.loc[vd_o['NM_M'].isin([1])]

,Formation,Well Name,Depth,GR,ILD_log10,DeltaPHI,PHIND,PE,NM_M,RELPOS
636,B2 LM,CRAWFORD,3062.5,66.266,0.443,4.505,13.995,2.553,1,0.200
637,B2 LM,CRAWFORD,3063.0,60.790,0.441,6.070,16.340,2.679,1,0.150
638,B2 LM,CRAWFORD,3063.5,54.670,0.444,6.250,16.740,3.350,1,0.100
639,B2 LM,CRAWFORD,3064.0,48.094,0.445,5.995,16.615,3.865,1,0.050
722,B4 LM,CRAWFORD,3105.5,70.526,0.731,-3.475,31.335,2.301,1,0.050
752,B5 LM,CRAWFORD,3122.0,69.179,0.692,6.110,19.220,3.114,1,0.063

Am I completely off base here? Just wondering if anyone else had a comment or has seen this.